name: github script

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

env:
  GIT_USER_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
  GIT_USER_NAME: "github-actions[bot]"
  BRANCH_NAME: workflow/bump-version
  PR_BODY: "Bump dependency packages version."
  PR_TITLE: "[bot] Bump dependency packages version."

jobs:
  create-pullrequest:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # cache: yarn

      - name: GitHub Author config
        run: |
          git config --global user.email '${{ env.GIT_USER_EMAIL }}' && \
          git config --global user.name '${{ env.GIT_USER_NAME }}'

      - name: Check branch exists
        run: |
          branch_is_existing=$(
            git fetch origin ${{ env.BRANCH_NAME }} &&
            echo true ||
            echo false
          )
          echo "BRANCH_EXISTS=${branch_is_existing}" >> $GITHUB_ENV

      - name: Create Working branch and bump version when not exists
        if: env.BRANCH_EXISTS == 'false'
        run: |
          git checkout -b ${{ env.BRANCH_NAME }} && \
          yarn version --patch --no-git-tag-version && \
          git add package.json && \
          git commit -m '[bot] bump version' && \
          git push -u origin HEAD

      - name: Pull and rebase working branch when exists
        if: env.BRANCH_EXISTS == 'true'
        run: |
          git switch ${{ env.BRANCH_NAME }} && \
          git pull --rebase origin main && \
          git push --force-with-lease

      - name: Create or Update pull request
        run: |
          gh pr edit ${{ env.BRANCH_NAME }} -b '${{ env.PR_BODY }}' -t '${{ env.PR_TITLE }}' && \
          gh pr reopen ${{ env.BRANCH_NAME }} || gh pr create -b main -t '${{ env.PR_TITLE }}' -b '${{ env.PR_BODY }}'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto Approve and merge pull request
        run: |
          gh pr review ${{ env.BRANCH_NAME }} -a && \
          gh pr merge ${{ env.BRANCH_NAME }} -m -d
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
