name: github script

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

env:
  BRANCH_NAME: workflow/bump-version

jobs:
  create-pullrequest:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # cache: yarn

      - name: GitHub Author config
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com" && \
          git config --global user.name "github-actions[bot]"

      - name: Check branch exists
        run: |
          branch_is_existing=$(
            git fetch origin ${{ env.BRANCH_NAME }} &&
            echo true ||
            echo false
          )
          echo "BRANCH_EXISTS=${branch_is_existing}" >> $GITHUB_ENV

      - name: Create Working branch when not exists
        if: env.BRANCH_EXISTS == 'false'
        run: git checkout -b ${{ env.BRANCH_NAME }}

      - name: Auto increment patch version when branch created
        if: env.BRANCH_EXISTS == 'false'
        run: yarn version --patch --no-git-tag-version

      - name: Commit & Push
        if: env.BRANCH_EXISTS == 'false'
        run: |
          git add package.json && \
          git commit -m '[bot] bump version' && \
          git push -u origin HEAD

      - name: Create Pull Request
        if: env.BRANCH_EXISTS == 'false'
        run: |
          gh pr create --base "main" --title "[Bot] Bump version" --body ""
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull and rebase working branch when exists
        if: env.BRANCH_EXISTS == 'true'
        run: |
          git switch ${{ env.BRANCH_NAME }} && \
          git pull --rebase origin main && \
          git push --force-with-lease
