name: github script

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  create-pullrequest:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # cache: yarn

      - name: GitHub Author config
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com" && \
          git config --global user.name "github-actions[bot]"

      - name: Create Working branch
        run: |
          git checkout -b workflow/bump-version

      - name: Auto increment patch version
        run: yarn version --patch --no-git-tag-version

      - name: Commit & Push
        run: |
          git add package.json && \
          git commit -m '[bot] bump version' && \
          git push -u origin HEAD

      - name: Open Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
